//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExam_suvorov.ZooShopDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string ArticleNumber { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
        public int DiscountAmount { get; set; }
        public string Manufacturer { get; set; }
        public string Category { get; set; }
        public int QuantityInStock { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public string Status { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
